"""PDF report template using NumberedCanvas for consistent page numbering."""

from datetime import date
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.utils import ImageReader
from pathlib import Path


class NumberedCanvas(canvas.Canvas):
    """Canvas subclass that tracks pages and displays 'page x of y' format."""

    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._codes = []
        
    def showPage(self):
        self._codes.append({'code': self._code, 'stack': self._codeStack})
        self._startPage()
        
    def save(self):
        """Add page info to each page (page x of y)"""
        # Reset page counter
        self._pageNumber = 0
        width, height = A4
        for code in self._codes:
            # Recall saved page
            self._code = code['code']
            self._codeStack = code['stack']
            self.setFont("Helvetica", 7)
            self.setLineWidth(0.8)
            # header
            # self.rect(20 * mm, height - 20 * mm, width - 40 * mm, 10 * mm, fill=0, stroke=1)
            # BASE_DIR = Path(__file__).resolve().parent
            # IMAGE_PATH = BASE_DIR / "QR.png"
            # im = ImageReader(IMAGE_PATH)
            # self.drawImage(im, 20*mm, height - 20 * mm, width=10*mm,height=10*mm,mask=None) 
            # self.drawCentredString(width/2, height - 15 * mm, "powered by HApi")


            # footer
            self.line(20 * mm, 25 * mm, width - 20 * mm, 25 * mm)
            #self.rect(20 * mm, 15 * mm, width - 40 * mm, 10 * mm, fill=0, stroke=1)
            self.drawString(20 * mm, 20 * mm, f"printed on {date.today():%Y-%m-%d}")
            self.drawCentredString(width/2, 20 * mm , "confidential")
            self.drawRightString(190 * mm, 20 * mm,
                "page %(this)i of %(total)i" % {
                   'this': self._pageNumber + 1,
                   'total': len(self._codes),
                }
            )

            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)


class PDFReportTemplate:
    """Template for generating consistent PDF reports."""
    
    def __init__(self, title="Sample Size Calculator", subtitle="", author="Sample Size Calculator"):
        self.title = title
        self.subtitle = subtitle
        self.author = author
        
    def generate_report(self, elements, output_path):
        """Generate a PDF report with numbered pages.
        
        Args:
            elements: List of ReportLab Flowable elements to include in the report
            output_path: Path where the PDF should be saved
            
        Returns:
            Tuple of (PDF bytes, output path)
        """
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )
        
        # Build the document with NumberedCanvas
        doc.build(elements, canvasmaker=NumberedCanvas)
        
        # Return PDF bytes and path
        with open(output_path, 'rb') as f:
            pdf_bytes = f.read()
            
        return pdf_bytes, output_path
    
    def create_standard_header(self):
        """Create standard report header."""
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=14,
            spaceAfter=6 * mm,
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=12 * mm,
        )
        
        header_elements = []
        
        if self.title:
            header_elements.append(Paragraph(self.title, title_style))
            
        if self.subtitle:
            header_elements.append(Paragraph(self.subtitle, subtitle_style))
            
        return header_elements
    
    def create_standard_footer(self):
        """Create standard report footer."""
        styles = getSampleStyleSheet()
        footer_text = "Generated by Sample Size Calculator - Medical Device Design Verification & Process Validation"
        
        return [
            Spacer(1, 6 * mm),
            Paragraph(footer_text, styles['BodyText']),
        ]
